#!/usr/bin/env bash

rm .coverage*
coverage run --parallel-mode --source='myproject,test' -m unittest discover -p '*.py' 'test'
coverage run --parallel-mode --source='myproject,test' -m behave 'test/features'
coverage combine
coverage report
